spring.application.name=PerfectPantry

spring.datasource.url=${URL}


spring.datasource.username=evanf
spring.datasource.password=${PASSWORD}
spring.sql.init.mode=always

# Without this stupid line the Springdoc UI doesn't work.
server.servlet.context-path=/