spring.application.name=PerfectPantry

spring.datasource.url=jdbc:postgresql://192.168.0.63:5432/PerfectPantry

#URL=jdbc:postgresql://192.168.0.63:5432/PerfectPantry,PASSWORD=Evfp2020@101

spring.datasource.username=evanf
spring.datasource.password=${PASSWORD}
spring.sql.init.mode=always

# Without this stupid line the Springdoc UI doesn't work.
server.servlet.context-path=/